### ISSUE TITLE
Having issues with Ansible role

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [proxmoxer/proxmoxer#11]
I've write an Ansible role to add the ssh public key to a proxmox server.

After the execution of the playbook:

```
---
- proxmox:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ target }}"
    #pubkey: "{{ public_keys.victor_home }}"
```

I got the next error:

```
**"msg": "authorization on proxmox cluster failed with exception: invalid literal for float(): 6.1-8"**
```

Talking on proxmox forums aswell
