### ISSUE TITLE
Unable to use cicustom with yaml input

### ISSUE THREAD

**Issue by harshguptaserver** [proxmoxer/proxmoxer#193]
Hello proxmoxer team,

I am a long time user of your library in my homelab. I find it great and really love the simplicity.

>> ##### aim : I am trying to create vm in proxmox using cloud-init from a .yml file ( https mode of communication to proxmox ) 

##### source:  :ref: https://proxmoxer.github.io/docs/latest/examples/cloud-init/
```
suggests : 
proxmox.nodes("<node_name>").qemu(clone_vm_id).config.set(
    ....
    cicustom="<explicit YAML cloud-config>",
    ....
)
```

Here is my sample code:

```

proxmox = ProxmoxAPI(
            cluster_config['host'],
            user=cluster_config['username'],
            password=cluster_config['password'],
            verify_ssl=cluster_config.get('verify_ssl', False),
            timeout=30
        )

def prepare_cloud_init_config(vmid, cloud_config_dir):
    cloud_init_file = os.path.join(cloud_config_dir, f'vm-{vmid}.yml')

    try:
        with open(cloud_init_file, 'r') as file:
            cloud_init_config = yaml.safe_load(file)
        return cloud_init_config
    except FileNotFoundError:
        logging.warning(f"No cloud-init configuration found for VM {vmid}")
        return None
    except Exception as e:
        logging.error(f"Error reading cloud-init config: {e}")
        return None

cloud_init_config = prepare_cloud_init_config(vmid, cloud_config_dir)
cloud_init_str = "#cloud-config\n" + yaml.dump(cloud_init_config)

# below code gives me error
update_cloud_init_config = proxmox.nodes(node).qemu(vmid).config.set(
                cicustom= cloud_init_str
            ) 
# my requirement is to read the cloud-config from a yml file and upload to server/set it for vm somehow
```
Error:
```
2024-12-14 22:47:58,199 - ERROR: Failed to create or configure VM: 400 Bad Request: Parameter verification failed. - {'cicustom': 'invalid format - value without key, but schema does not define a default key\n'}
```

##### desired solution : read the yml file and create cloud-init of the vm ( the yml file has multiple keys and config ) 

Note: the yml file works fine if i use  shell command by copying yml manually : 
```
this_ci_custom = "qm set {0} --cicustom \"{1}\"".format(vm_id, vm_ci_location)
```

Sample yml file
```
#cloud-config
hostname: test-faas-01
manage_etc_hosts: true
user: pi
chpasswd:
  expire: False
users:
  - default

ssh_pwauth: true

package_upgrade: true
package_update: true


packages:
 - wget
 - nload
 - htop
 - curl
 - net-tools
 - python3-dev
 - python3-pip
 - qemu-guest-agent

apt:
  primary:
    - arches: [default]
      uri: http://us.archive.ubuntu.com/ubuntu/



runcmd:
 - date >> /etc/birthday_vm
 - systemctl enable --now qemu-guest-agent
final_message: "The system is finally up, after $UPTIME seconds"
power_state:
  delay: now
  mode: reboot
  message: Bye Bye
  timeout: 30
  condition: True
ssh_authorized_keys:
  - ssh-rsa AAAAB......8V harsh@gd03

manage_resolv_conf: true
resolv_conf:
  nameservers: [10.0.0.20, 10.0.0.1]
locale: un_US
```
