### ISSUE TITLE
Throws error when used under Python3.13.x

### ISSUE THREAD

**Issue by cloudcodger** [proxmoxer/proxmoxer#198]
I have an Ansible playbook that use a Role that uses modules based off the `community.general` `proxmox` module, except that they use the `openssh` backend. This works fine with Python 3.12.x but now fails with Python 3.13.x with the error `Chosen backend requires 'openssh_wrapper' module`.

This message is coming from `proxmoxer` when it checks to see if the `openssh_wrapper` module is installed and for some reason it fails even when the module is there.

Example of the playbook running:

```
(venv129) cloudcodger/showcase % python3 --version
Python 3.12.9
(venv129) cloudcodger/showcase % ansible-playbook test_pve.yml

PLAY [Configure the Proxmox Datacenter.] ***************************************************************************************************

TASK [Test calling openssh module.] ********************************************************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Example of the playbook run with the error:

```
(venv132) cloudcodger/showcase % python3 --version
Python 3.13.2
(venv132) cloudcodger/showcase % ansible-playbook test_pve.yml

PLAY [Configure the Proxmox Datacenter.] ***************************************************************************************************

TASK [Test calling openssh module.] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Chosen backend requires 'openssh_wrapper' module\n\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
In both cases, using `proxmoxer` module version `2.2.0`.

Here is the `test_pve.yml` playbook that is failing with Python 3.13.

```
---
- name: Configure the Proxmox Datacenter.
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Test calling openssh module.
      cloudcodger.proxmox_openssh.proxmox_group:
        api_host: gadget1
        api_user: root
        api_port: 22
        api_sudo: false
        group: Admin
        state: present
```
